# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=4096)),
                ('description', models.CharField(max_length=4096)),
                ('location', models.CharField(max_length=1024)),
                ('registration_deadline', models.DateTimeField()),
                ('registration_link', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
